### PR TITLE
Objective-C Support

### PR DESCRIPTION
**Pull request by Patrick-Kladek**
### Description

Allows usage of this library from objc code.

### Tasks

- [x] Mark classes & protocols with `@objc`
- [x] Change `class` to `AnyObject` in protocols to fix warnings
- [x] Apply recommended Xcode settings

### Infos For Reviewer

Even though Issue #13 was closed I figured out that supporting objc was super easy. 
I've started of 5.0 tag but can't create a PR from this commit and can't use 5.0.1 (master) as installation via cocoapods fails with following warning:

There is also an existing issue #188. How should we continue with this?

Bildschirmfoto 2021-10-20 um 13 35 09

### CODE REVIEW

**Comment by brendand** [comment]
Any chance 3 years later this could get merged into master?

**Comment by 3lvis** [comment]
Not sure why "Copy Pods Resources" was removed. Everything else seems ok.

**Comment by 3lvis** [comment]
Merged into the objc branch for testing.

**Comment by 3lvis** [comment]
@Patrick-Kladek thanks for your contribution.

**Pull request merged**
