### PR TITLE
Add Support For SPM

### PR DESCRIPTION
**Pull request by gbreen12**
This adds support for Swift Package Manager

A couple issues-
Main one: This probably breaks support of CocoaPods (I'm not sure). SPM requires you to access resources via a Bundle.module call that doesn't seem to exist in a normal Xcode project swift code. I don't know how to get around that.

Another: I moved the images into an xcassets and the Localization down into the Sources so that they would be included in the Swift Package.

Last: I remerged today from master and now the footer is not showing. I've tried setting hideFooterView = false but it isn't working.

This probably isn't the full support we're wanting but I think it's a good start.

### CODE REVIEW

**Comment by 3lvis** [comment]
Thanks for your work @gbreen12! The footer might be because of an earlier PR I merged. Should probably roll back if it's causing issues.

**Comment by 3lvis** [comment]
I'll merge this and we can look into fixing the CocoaPods part if that's an issue. I have other libraries where both SPM and CocoaPods work hand by hand so it should be possible here as well.

**Comment by gbreen12** [comment]
Yeah I know there's a way to do it but I've never created a cocoapods library before and I didn't have the time to figure that part out. Thanks!

**Comment by 3lvis** [comment]
Let's just hope someone is bothered by CocoaPods being broken and fixes it. :D

**Pull request merged**
